apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 036253061913.dkr.ecr.eu-west-1.amazonaws.com/devops:latest
    newTag: 23