apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-app

  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ma6075707-blip/Devops-project.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true